title: "Andy Minseo Park"

author: andymspark@gmail.com

description: > 
  Webpage Protofolio

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

nav:
  - title: About
    url: /about/
  - title: Research
    url: /research/
  - title: Publication
    url: /publication/
  - title: Archive
    url: /archive/
